import type { Experience } from "./experience.types";

export const experiences: Experience[] = [
  {
    id: "druckhaus",
    img: "/druckhaus-logo.png",
    imageFit: "contain",
    company: "Druckhaus GmbH",
    location: "Bochum, Germany",
    position: "Software Engineer (Hybrid)",
    period: "FEBRUARY 2026 - PRESENT",
    color: "#009fce",
    achievements: [
      "Eliminated duplicate validation logic across 4 repositories with a tested, shared TypeScript package supporting ESM and CommonJS.",
      "Standardized UI behaviour across 3 products through a reusable React component library, enabling developers to adopt documented, accessibility-tested components instead of rebuilding forms, navigation, and upload interactions.",
      "Unified order management and status tracking across 2 e-commerce platforms by building an internal management tool with React, TypeScript, Node.js, MongoDB, and Docker.",
      "Built end-to-end account-deletion workflows with customer requests and cancellation, backend access controls, admin management, and responsive transactional emails.",
      "Improved frontend architecture with prerendered HTML, route-specific metadata, and social previews to support page discoverability and sharing; fixed Nginx routing to resolve hydration mismatches.",
      "Standardized package and application releases across repositories with automated quality gates, semantic versioning, and staging deployments, leveraging Grafana for monitoring across products.",
      "Built a full-stack registration experience with address autocomplete, stronger phone and postal-address validation, and consistent frontend/backend error handling.",
      "Leveraged AI-assisted development tools to accelerate delivery and actively contributed to Scrum planning and retrospectives to improve team workflows.",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "MongoDB",
      "Docker",
      "Nginx",
      "Grafana",
    ],
  },
  {
    id: "pickshare",
    img: "/pickshare.jpeg",
    company: "Pickshare GmbH",
    location: "Dortmund, Germany",
    position: "Software Engineer (Hybrid)",
    period: "JUNE 2025 - DECEMBER 2025",
    color: "#4fa6ff",
    achievements: [
      "Introduced delivery-trust KPIs and built interactive admin dashboards using React, Next.js, and Recharts, improving visibility into delivery performance.",
      "Designed and built a multi-slot logistics booking system with React, TypeScript, and Node.js REST APIs, collaborating with the CTO and designers to simplify scheduling.",
      "Designed a reusable, testable React table component system for an internal admin platform, standardizing table behaviour and improving performance.",
      "Owned full-stack architecture for a partner-portal tour assignment system, collaborating with backend engineers on REST APIs to streamline operational workflows and improve productivity by 20%.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Recharts",
      "Node.js",
      "REST APIs",
    ],
  },
  {
    id: "knime",
    img: "/knime-logo.png",
    company: "KNIME GmbH",
    location: "Berlin, Germany",
    position: "Software Engineer (Hybrid)",
    period: "JANUARY 2024 - JANUARY 2025",
    color: "#f7a440",
    achievements: [
      "Owned and evolved an open-source Vue.js component library published on npm, building accessible components using TDD, with Storybook documentation and visual testing.",
      "Developed the core UI platform for a SaaS analytics product using Vue.js and TypeScript, improving usability, performance, and design-system consistency.",
      "Integrated Vitest unit and component tests and Playwright end-to-end tests into CI/CD pipelines to support reliable releases.",
      "Built a reusable multi-file upload component with Vue.js, TypeScript, and Tailwind CSS, extending Java backend services to support dynamic configuration.",
      "Implemented a scalable multi-file upload widget using Vue.js, TypeScript, and Tailwind CSS, built as a reusable, testable UI component, and implemented Java backend services to enable dynamic configuration.",
      "Integrated an LLM-powered chatbot using the Vercel AI SDK, enabling real-time response streaming.",
      "Collaborated with product owners, designers, and backend engineers to deliver user-facing improvements through iterative development, pair programming, and Scrum retrospectives.",
    ],
    technologies: [
      "Vue.js",
      "TypeScript",
      "Tailwind CSS",
      "Java",
      "Vitest",
      "Playwright",
      "Storybook",
      "Vercel AI SDK",
    ],
  },
  {
    id: "programmers-house",
    company: "Programmers House",
    location: "Tehran, Iran",
    position: "Software Engineer (Hybrid)",
    period: "JANUARY 2020 - DECEMBER 2022",
    color: "#5ba374",
    achievements: [
      "Owned end-to-end delivery of React and Node.js web applications, working directly with customers to translate business requirements into accessible, maintainable SPA and SSR solutions.",
      "Integrated automated tests using Jest, Testing Library, and Cypress into CI/CD pipelines, supported by structured code reviews to improve release reliability.",
      "Built real-time features with React, TypeScript, and WebSockets to synchronize slot availability and status updates across the application.",
      "Designed frontend architecture and reusable React components, shaping an internal design system and managing complex state for rich media, multi-step workflows, and forms.",
      "Designed and integrated Node.js REST APIs backed by PostgreSQL, defining clear API contracts and implementing error handling, retries, and graceful fallbacks in React and TypeScript clients.",
    ],
    technologies: [
      "React",
      "Node.js",
      "TypeScript",
      "REST APIs",
      "PostgreSQL",
      "WebSockets",
      "Jest",
      "Testing Library",
      "Cypress",
    ],
  },
];
